# Generated by Django 5.1.5 on 2025-01-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('user', models.CharField(max_length=100, verbose_name='Usuario')),
                ('token', models.PositiveIntegerField(max_length=4, unique=True, verbose_name='Token')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('tipousuario', models.CharField(blank=True, choices=[('Admin', 'Administrador'), ('Clien', 'Cliente')], max_length=5, null=True, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateField(auto_now=True, verbose_name='Fecha de consulta')),
                ('horaconsulta', models.TimeField(auto_now=True, verbose_name='Hora consulta')),
                ('precioconsulta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.paciente')),
            ],
        ),
    ]
