# Generated by Django 5.1.5 on 2025-01-25 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistem.paciente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.PositiveIntegerField(unique=True, verbose_name='Token'),
        ),
    ]
