# Generated by Django 5.1.5 on 2025-01-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0002_remove_usuario_nombre_usuario_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=100, unique=True, verbose_name='Usuario'),
        ),
    ]
