# Generated by Django 4.2.18 on 2025-02-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0003_alter_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(primary_key=True, serialize=False)),
                ('fechacita', models.DateField(auto_now=True, verbose_name='Fecha de cita')),
                ('horacita', models.TimeField(auto_now=True, verbose_name='Hora cita')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.paciente')),
            ],
        ),
    ]
