# Generated by Django 4.2.18 on 2025-02-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0006_alter_cita_fechacita_alter_cita_horacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dia',
            field=models.CharField(default='1', max_length=7, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='cita',
            name='semana',
            field=models.PositiveIntegerField(default='55', verbose_name='Semana'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prueba',
            field=models.CharField(default=1, max_length=500, verbose_name='prueba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechacita',
            field=models.DateField(null=True, verbose_name='Fecha de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horacita',
            field=models.CharField(blank=True, choices=[('1', '8:00 - 9:00'), ('2', '9:00 - 10:00'), ('3', '10:00 - 11:00'), ('4', '11:00 - 12:00'), ('5', '01:00 - 02:00'), ('6', '02:00 - 03:00'), ('7', '03:00 - 04:00'), ('8', '04:00 - 05:00'), ('9', '05:00 - 06:00')], max_length=11, null=True, verbose_name='Hora cita'),
        ),
    ]
