# Generated by Django 4.2.18 on 2025-02-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0007_cita_dia_cita_semana_consulta_prueba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='prueba',
        ),
    ]
