# Generated by Django 4.2.18 on 2025-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0008_remove_consulta_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='semana',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Les', 'Lesion'), ('Pat', 'Patologia')], max_length=3, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechacita',
            field=models.DateField(verbose_name='Fecha de cita'),
        ),
    ]
