# Generated by Django 4.2.18 on 2025-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0009_remove_cita_dia_remove_cita_semana_consulta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horacita',
            field=models.CharField(choices=[('1', '8:00 - 9:00'), ('2', '9:00 - 10:00'), ('3', '10:00 - 11:00'), ('4', '11:00 - 12:00'), ('5', '01:00 - 02:00'), ('6', '02:00 - 03:00'), ('7', '03:00 - 04:00'), ('8', '04:00 - 05:00'), ('9', '05:00 - 06:00')], max_length=11, verbose_name='Hora cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='precioconsulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('Lesion', 'Lesion'), ('Patologia', 'Patologia')], max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
